//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravintolaskuri.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ravintolaskuri.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _in {
            get {
                object obj = ResourceManager.GetObject("_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _out {
            get {
                object obj = ResourceManager.GetObject("_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koska kyseessä on amatööriprojekti ja mahdollisia bugeja voi olla useita, joita ei ole voitu testaamalla löytää, on suotavaa, että aktiivisessa käytössä otetaan ruokataulukosta ja päiväkirjasta varmuuskopiot talteen. Ne voidaan tarvittaessa ladata takasin ohjelmaan ilman, että tietoja menetetään lopullisesti. Tiedoston on oltava json-tiedoston muodossa (.json), jona se tallennetaan oletuksena..
        /// </summary>
        internal static string BackupInstruction {
            get {
                return ResourceManager.GetString("BackupInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varmuuskopiointi.
        /// </summary>
        internal static string BackupTitle {
            get {
                return ResourceManager.GetString("BackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruokien tietoja voidaan katsoa klikkaamalla ruokaa vasemman puolen laatikoista. Ruoka voidaan lisätä tuplaklikkaamalla, jolloin se näytetään Valitut-listassa. Ohjelma laskee kaikkien valittujen ruokien yhteiskalorit jne. Ruoka poistetaan listasta tuplaklikkaamalla sitä. Koko lista tyhjennetään painamalla Tyhjennä-nappia. Visuaalisena apuna voidaan käyttää alhaalla olevaa edistymispalkkia kirjoittamalla tekstikenttään tavoittelemansa kalorimäärän. Luvun voi lisätä vain Valitut-listan ollessa tyhjänä..
        /// </summary>
        internal static string CalculatorInstruction {
            get {
                return ResourceManager.GetString("CalculatorInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laskurin ohje.
        /// </summary>
        internal static string CalculatoTitle {
            get {
                return ResourceManager.GetString("CalculatoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  kcal.
        /// </summary>
        internal static string CaloriesText {
            get {
                return ResourceManager.GetString("CaloriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makropäiväkirjan tyhjentäminen.
        /// </summary>
        internal static string ClearDiaryTitle {
            get {
                return ResourceManager.GetString("ClearDiaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAROITUS! Valitsemalla YES kaikki kalenteriin tallennetut tiedot pyyhitään, eikä tietoja voida enää palauttaa. Haluatko varmasti poistaa kaikki tiedot?.
        /// </summary>
        internal static string ClearDiaryWarning {
            get {
                return ResourceManager.GetString("ClearDiaryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruokataulun tyhjentäminen.
        /// </summary>
        internal static string ClearFoodtableTitle {
            get {
                return ResourceManager.GetString("ClearFoodtableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAROITUS! Valitsemalla YES koko ruokataulu tyhjennetään, eikä tietoja voida enää palauttaa. Haluatko varmasti poistaa kaikki tiedot?.
        /// </summary>
        internal static string ClearFoodtableWarning {
            get {
                return ResourceManager.GetString("ClearFoodtableWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close3 {
            get {
                object obj = ResourceManager.GetObject("close3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haluatko varmasti poistaa tiedot?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vahvista poisto.
        /// </summary>
        internal static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makropäiväkirjalla voidaan pitää kirjaa syödyistä kaloreista jne. päiväkohtaisesti. Laskurissa olevat tiedot voidaan siirtää päiväkirjaan valitsemalla päivä ja painamalla Lisää-nappia. Vastaavasti ne voidaan poistaa kyseisen päivän kohdalta. Alla olevaan diagrammiin piirretään pylväitä niiden päivien kohdalle, joihin on lisätty dataa. Diagrammi esittää kaloreiden määrän tiettyinä päivinä. Diagrammi näyttää aina vain valitun kuukauden tiedot. Päiväkirja tallentuu automaattisesti..
        /// </summary>
        internal static string DiaryInstruction {
            get {
                return ResourceManager.GetString("DiaryInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Päiväkirjan ohje.
        /// </summary>
        internal static string DiaryTitle {
            get {
                return ResourceManager.GetString("DiaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruoan erengiatiedoissa voi olla virheitä..
        /// </summary>
        internal static string EnergyShareCheck {
            get {
                return ResourceManager.GetString("EnergyShareCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  E%.
        /// </summary>
        internal static string EnergyShareText {
            get {
                return ResourceManager.GetString("EnergyShareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohjelma tallentaa vanhan tiedoston päälle. Haluatko varmasti korvata vanhat tiedot?.
        /// </summary>
        internal static string FileSaveConfirmation {
            get {
                return ResourceManager.GetString("FileSaveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vahvista tallennus.
        /// </summary>
        internal static string FileSaveTitle {
            get {
                return ResourceManager.GetString("FileSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Food {
            get {
                object obj = ResourceManager.GetObject("Food", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saman niminen ruoka on jo olemassa..
        /// </summary>
        internal static string FoodExist {
            get {
                return ResourceManager.GetString("FoodExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruokaa lisättäessä sille annetaan uniikki nimi. Kaloreiden jne. määrät annetaan kilokaloreina ja grammoina käyttäen kokonaislukuja. Kategoriaksi valitaan joku neljästä vaihtoehdosta. Info-kenttä ei ole pakollinen, mutta siihen voidaan lisätä omia huomioita kyseistä ruoasta. HUOM! Muista aina tallentaa taulukko ennen ohjelman sulkemista, jos olet lisännyt tai poistanut ruoan..
        /// </summary>
        internal static string FoodtableInstruction {
            get {
                return ResourceManager.GetString("FoodtableInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taulukon ohje.
        /// </summary>
        internal static string FoodtableTitle {
            get {
                return ResourceManager.GetString("FoodtableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        internal static string GramsText {
            get {
                return ResourceManager.GetString("GramsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info: .
        /// </summary>
        internal static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virhe avattaessa json-tiedostoa! Tiedoston datassa virheitä..
        /// </summary>
        internal static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap q3 {
            get {
                object obj = ResourceManager.GetObject("q3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tallentaminen epäonnistui. Tarkista polku!.
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anna tiedot kokonaislukuina ja valitse kategoria!.
        /// </summary>
        internal static string ValidateError {
            get {
                return ResourceManager.GetString("ValidateError", resourceCulture);
            }
        }
    }
}
